### ISSUE TITLE
Deprecated Node Module

### ISSUE THREAD

**Issue by dcastellon0001** [continuous-software/42-cent-base#7]
Hi. I'm new to contributing, but I think this is a really nice project to get started in, so I was looking at the code to get a feel for how it all works together. I noticed that 42-cent-base/lib/BaseGateway contains the deprecated node module [util._extend](https://nodejs.org/api/util.html#util_util_extend_target_source) and was wondering if I could switch it to [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

**Comment by kytwb** [comment]
Thank you for coming up with a pull request. I will proceed to patch the version of the module and publish! 🙏
